---
title: "Score_module"
format: html
editor: visual
---

```{r}
library(readr)
library(ggplot2)
library(dplyr)
library(tidyr)
library(knitr)
library(quantreg)
library(forcats)
library(stringr)

```

```{r}

openpowerlifting <- read_csv(here::here("joshlarson/data/openpowerlifting-2025-03-22/openpowerlifting-2025-03-22-c4367451.csv"))

```

```{r}
tidy <-openpowerlifting %>%
  group_by(Name) %>%
  arrange(desc(Date), 
          .by_group = TRUE) %>% # group_by(name) %>%
  slice(1) %>%                              # slice_max(date, n=1)
  filter(
    (Tested == "Yes") 
    & (Event == "SBD") 
    & Equipment %in% c("Single-ply","Raw") 
    & !(Place %in% c("DQ", "NS", "G", "DD"))
    )%>%
  drop_na(Age, Best3SquatKg, Best3BenchKg, Best3DeadliftKg) 
  


# DQ, NS, G, DD
```

```{r}
write_csv(tidy, "tidy_powerlift.csv")
```

```{r}
# Male Podium Lifters
podium_male<-
  tidy %>%
  filter(Sex == "M")
write_csv(podium_male, "podium_male_lifters.csv")
```

```{r}
# Female Podium Lifters
podium_female<-
  tidy %>%
  filter(Sex == "F")
write_csv(podium_female, "podium_female_lifters.csv")

```

```{r}
male <- read_csv(here::here("joshlarson/data/podium_male_lifters.csv"))
female <- read_csv(here::here("joshlarson/data/podium_female_lifters.csv"))

```

```{r}
male %>%
  group_by(AgeClass) %>%
  tally()
  sample_n(size = 500)

female %>%
  group_by(AgeClass) %>%
  
```

```{r}
library(quantreg)
```

```{r}
# Testing Models: MALES
set.seed(1)
test_male <- male %>%
  group_by(AgeClass) %>%
  group_modify(~ if (nrow(.x) >= 500) sample_n(.x, 500) else .x) %>%
  ungroup() %>%
  select(1:10, 15, 20, 25:35) %>%
  pivot_longer(
    cols = 11:13,
    names_to = "Lift",
    values_to = "Best_lift"
  ) %>%
  mutate(
    AgeClass = fct_relevel(factor(AgeClass),
                           c("5-12", "13-15", "16-17", "18-19",
                             "20-23", "24-34", "35-39", "40-44", "45-49", "50-54",
                             "55-59", "60-64", "65-69", "70-74", "75-79", "80-999"))
  )
  
  
test_male
# Median Regression: tau = 0.5
test_male %>%
  rq(TotalKg ~ Age, tau = .5, data = .)

write_csv(test_male, "tidy_male_lifters_quantreg.csv")
```

```{r}
#| fig-height: 14
#| fig-width: 9
test_male <- test_male %>%
  mutate(
    Lift = str_remove(Lift, pattern = "Best3") %>%
      str_remove(pattern = "Kg")
  ) 

Best_m_lift_plot <- ggplot(test_male, aes(x = Age, y = Best_lift)) +
  geom_point(alpha = 0.5, size = 1.2,
            ) +
  
  # Smooth spline quantile regression
  #geom_quantile(
   # quantiles = c(0.1, 0.9),
   # method = "rqss",
    #lambda = 2.5,
    #color = "red",
    #linewidth = 1
  #) +
  
  # Polynomial quantile regression (2nd degree)
  geom_quantile(
    quantiles = c(0.1),
    method = "rq",
    formula = y ~ poly(x, 4),
    color = "blue",
    linewidth = 1
  ) +
  geom_quantile(
    quantiles = (0.9),
    method = "rq",
    formula = y ~ poly(x, 4),
    color = "green",
    linewidth = 1
  ) +
  facet_wrap(~ Lift, ncol = 1) + theme_classic() + coord_cartesian(ylim = c(0,NA)
                                                                   ) +
  geom_vline(xintercept = c(28,35), linetype = "dashed", color = "red") +
  labs(
    x = "Age (years)",
    y = "Best Lift (kg)",
    title = "Best Lifts Across Age for Male Lifters"
  ) +
   theme(
    axis.title = element_text(size = 18, face = "bold"),
    axis.text = element_text(size = 16),
    strip.text = element_text(size = 18, face = "bold"),
    plot.title = element_text(size = 22, face = "bold", hjust = 0.5)
  )

Best_m_lift_plot
#4th order polynomial to represent the quantiles (.1, .9)
```

```{r}
ggsave("best_m_lift_plot.png", Best_m_lift_plot, width = 9, height = 14)
```

```{r}
# Testing Models: FEMALES
set.seed(1)
test_female <- female %>%
  group_by(AgeClass) %>%
  group_modify(~ if (nrow(.x) >= 500) sample_n(.x, 500) else .x) %>%
  ungroup() %>%
  select(1:10, 15, 20, 25:35) %>%
  pivot_longer(
    cols = 11:13,
    names_to = "Lift",
    values_to = "Best_lift"
  ) %>%
  mutate(
    AgeClass = fct_relevel(factor(AgeClass),
                           c("5-12", "13-15", "16-17", "18-19",
                             "20-23", "24-34", "35-39", "40-44", "45-49", "50-54",
                             "55-59", "60-64", "65-69", "70-74", "75-79", "80-999"))
  )
  
  
test_female
write_csv(test_female, "tidy_female_lifters_quantreg.csv")
```

```{r}
#| fig-height: 14
#| fig-width: 9
ggplot(test_female, aes(x = Age, y = Best_lift, color = AgeClass)) +
  geom_point(alpha = 0.5, size = 1.2,
            ) +
  
  # Smooth spline quantile regression
  geom_quantile(
    quantiles = c(0.1, 0.9),
    method = "rqss",
    lambda = 0.1,
    color = "red",
    linewidth = 1
  ) +
  
  # Polynomial quantile regression (2nd degree)
  geom_quantile(
    quantiles = c(0.1, 0.9),
    method = "rq",
    formula = y ~ poly(x, 4),
    color = "blue",
    linewidth = 1,
    linetype = "dashed"
  ) +
  facet_wrap(~ Lift, ncol = 1) + 
  theme_minimal() + 
  scale_color_viridis_d(option = "C") 

```
